server:
  port: 9002

spring:
  application:
    name: hello-for-feign


eureka:
  instance:
    hostname: localhost #ÅäÖÃÖ÷»úÃû
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka