server:
  port: 7011
spring:
  application:
    name: micro-service1

eureka:
  instance:
    hostname: localhost #配置主机名
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/   #配置Eureka Server